
@BASEURL = http://localhost:5000/api
 
//
GET {{BASEURL}}/users
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDVkOThiMmU3YjBjOTRkMjQ5ZDMxZDQiLCJlbWFpbCI6ImtvcmF5MUBnbWFpbC5jb20iLCJpYXQiOjE2MTY3NDY2ODEsImV4cCI6MTYxNjc1MDI4MX0.CcavgezQhl1oP8Ir0jKlIgh-d4zj_20PtjyGIsoRKtU

### 
//GET id
GET {{BASEURL}}/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDc2OGFlZTJmM2VkODAzZTQyOTkyMjAiLCJlbWFpbCI6Im9ybmVrZ2lyaXNAZ21haWwuY29tIiwiaWF0IjoxNjE4NDA2NzcxLCJleHAiOjE2MTg0MTAzNzF9.eFr_JfkDGjdjZDQgVwgQXfzSGuX5N4ZUYFOjvvwo_lU

### 
//  POST JSON
POST {{BASEURL}}/users
Content-Type: application/json

{
    "name" : "reco",
    "surname" : "reco",
    "userName" : "reco",
    "email" : "reco@gmail.com",
    "password" : "123456"    
}

###
//  POST JSON
POST https://react-yazi-yorum.herokuapp.com/posts
Content-Type: application/json

{
    "title": "hile",
     "content": "hile2"   
}

###
//  Giris
POST {{BASEURL}}/users/login
Content-Type: application/json

{
    "email" : "ornekgiris@gmail.com",
    "password" : "123456"    
}

###
// urlencoded
POST {{BASEURL}}/users
Content-Type: application/x-www-form-urlencoded

isim=korssay&yas=23

###
PATCH {{BASEURL}}/users/605cf397effb8d278c7e5f61
Content-Type: application/json

{
    "surname" : "recaii"
}

###
PATCH {{BASEURL}}/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDVkNjYwMzE2MDMwMjRkMzg1M2M2NzIiLCJlbWFpbCI6ImtyeWtyeUBnbWFpbC5jb20iLCJpYXQiOjE2MTY3MzcyNjgsImV4cCI6MTYxNjc0MDg2OH0.5N9ssxalfxL_og8njSZoxL4RvFzEEaFzFysIqlv0BEs

{
    "name" : "plray"
}

###
DELETE {{BASEURL}}/users/605cdf18cfa8d13420bd74e2
Content-Type: application/json

###
DELETE {{BASEURL}}/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDVkODU1NTAzM2NjNjE5NTQyZDRlNTQiLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTYxNjc4Mzk1NywiZXhwIjoxNjE2Nzg3NTU3fQ.oGm7CWZXTCA0hRt8pUgmXDrGy2ERW5qfUYaF5XIRLqU


###
GET {{BASEURL}}/users/deleteAll
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDVkODU1NTAzM2NjNjE5NTQyZDRlNTQiLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTYxNjc0ODkzNiwiZXhwIjoxNjE2NzUyNTM2fQ.qyzyjCr2lnhbrg8FKxp9kPgK7cVVQavvHbnb9i70AeQ
